#!/bin/bash -e

# Downloads Firefox and unzips to the user's home directory,
# with a desktop launcher

TEMP_DIR=`mktemp -d`

exit_with_error() {
    echo $1
    rm -rf ${TEMP_DIR}
    exit 1
}

USERID=$(id -u)
if [ "$USERID" == "0" ]; then
    exit_with_error "Program cannot be run as superuser"
fi

DEB_ARCH=`dpkg --print-architecture`
case ${DEB_ARCH} in
    amd64) ;; # Only 64-bit Intel architectures are supported
    *) exit_with_error "Unsupported architecture ${DEB_ARCH}"
       ;;
esac

DEST_DIR=~/.local/share/eos-third-party-apps/firefox
FLASH_DIR=${DEST_DIR}/flash
PLUGINS_DIR=~/.mozilla/plugins
DESKTOP_DIR=~/.local/share/applications
WGET_COMMAND="wget -c --tries=5"

FIREFOX_URL="https://download.mozilla.org/?product=firefox-latest&os=linux64"
FIREFOX_LOCALIZED_URL=
FIREFOX_FILENAME=firefox.tar.xz
FIREFOX_LANG=

JAVA_BUILD=8u112-b15
JAVA_VERSION=`echo ${JAVA_BUILD} | cut -f 1 -d -`
JAVA_FILENAME=jre-${JAVA_VERSION}-linux-x64.tar.gz
JAVA_URL_FILENAME=http://download.oracle.com/otn-pub/java/jdk/${JAVA_BUILD}/${JAVA_FILENAME}

# While the following would be a faster download of the current version,
# previous versions are often removed from the server, so it is safest
# for an automated script to use the stable version in the archive
# http://fpdownload.macromedia.com/get/flashplayer/pdc/11.2.202.643/install_flash_player_11_linux.x86_64.tar.gz
FLASH_VERSION=11.2.202.643
FLASH_SHA256SUM="1a79f38f7153d436083b5a6b5d0f38e0c4cd345e83e7d050152452057f83350a"
FLASH_FILENAME=fp_${FLASH_VERSION}_archive.zip
FLASH_URL_FILENAME=http://download.macromedia.com/pub/flashplayer/installers/archive/${FLASH_FILENAME}

ICON_FILENAME=firefox.png
ICON_URL_FILENAME=https://raw.githubusercontent.com/endlessm/eos-customer-support/master/data/${ICON_FILENAME}

get_firefox_lang() {
    # List of supported Firefox languages, from https://download-installer.cdn.mozilla.net/pub/firefox/releases/latest/README.txt
    FIREFOX_LANGS="ach af an ar as ast az be bg bn-BD bn-IN br bs ca cs cy da de dsb el en-GB en-US en-ZA eo es-AR es-CL es-ES es-MX et eu fa ff fi fr fy-NL ga-IE gd gl gu-IN he hi-IN hr hsb hu hy-AM id is it kk km kn ko lij lt lv mai mk ml mr ms nb-NO nl nn-NO or pa-IN pl pt-BR pt-PT rm ro ru si sk sl son sq sr sv-SE ta te th tr uk uz vi xh zh-CN zh-TW"

    # Find the closest supported Firefox for the user's current language
    locale=`echo ${LANG} | cut -f 1 -d . | sed s/_/-/`
    lang=`echo ${locale} | cut -f 1 -d -`
    for l in ${FIREFOX_LANGS}
    do
        if [ ${l} == ${locale} ]
        then
            FIREFOX_LANG=${l}
            break
        fi
    done

    if [ -z ${FIREFOX_LANG} ]; then
        for l in ${FIREFOX_LANGS}
        do
            if [ ${l} == ${lang} ]
            then
                FIREFOX_LANG=${l}
                break
            fi
        done
    fi

    if [ -z ${FIREFOX_LANG} ]; then
        if [ ${lang} == es ]; then
            FIREFOX_LANG=es-MX
        else
            FIREFOX_LANG=en-US
        fi
    fi
}

download_packages() {
    echo "Downloading ${FIREFOX_FILENAME}"
    FIREFOX_LOCALIZED_URL="${FIREFOX_URL}&lang=${FIREFOX_LANG}"
    if ! ${WGET_COMMAND} "${FIREFOX_LOCALIZED_URL}" -O "${TEMP_DIR}/${FIREFOX_FILENAME}"; then
        exit_with_error "Failed to download ${FIREFOX_LOCALIZED_URL}"
    fi

    echo "Downloading ${JAVA_FILENAME}"
    if ! ${WGET_COMMAND} --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" ${JAVA_URL_FILENAME} -O "${TEMP_DIR}/${JAVA_FILENAME}"; then
        exit_with_error "Failed to download ${JAVA_URL_FILENAME}"
    fi

    echo "Downloading ${FLASH_FILENAME}"
    if ! ${WGET_COMMAND} "${FLASH_URL_FILENAME}" -O "${TEMP_DIR}/${FLASH_FILENAME}"; then
        exit_with_error "Failed to download ${FLASH_URL_FILENAME}"
    fi

    echo "Verifying ${TEMP_DIR}/${FLASH_FILENAME}"
    echo "${FLASH_SHA256SUM} ${TEMP_DIR}/${FLASH_FILENAME}" | sha256sum -c > /dev/null 2>&1 || \
    {
        exit_with_error "sha256sum mismatch ${TEMP_DIR}/${FLASH_FILENAME}"
    }

    echo "Downloading icon"
    if ! ${WGET_COMMAND} "${ICON_URL_FILENAME}" -O "${TEMP_DIR}/${ICON_FILENAME}"; then
        exit_with_error "Failed to download ${ICON_URL_FILENAME}"
    fi
}

install_packages() {
    echo "Removing old version if installed"
    rm -rf ${DEST_DIR}
    rm -f ${PLUGINS_DIR}/libnpjp2.so
    rm -f ${PLUGINS_DIR}/libflashplayer.so

    mkdir -p ${DEST_DIR}
    mkdir -p ${PLUGINS_DIR}
    mkdir -p ${FLASH_DIR}

    echo "Installing ${TEMP_DIR}/${FIREFOX_FILENAME}"
    if ! tar -xf ${TEMP_DIR}/${FIREFOX_FILENAME} -C ${DEST_DIR} ; then
        exit_with_error "Cannot unpack tar file ${FIREFOX_FILENAME}"
    fi

    echo "Installing ${TEMP_DIR}/${JAVA_FILENAME}"
    if ! tar -xf ${TEMP_DIR}/${JAVA_FILENAME} -C ${DEST_DIR} ; then
        exit_with_error "Cannot unpack tar file ${JAVA_FILENAME}"
    fi
    
    echo "Installing ${TEMP_DIR}/${FLASH_FILENAME}"
    pushd ${TEMP_DIR}
    if ! unzip ${TEMP_DIR}/${FLASH_FILENAME} ; then
        exit_with_error "Cannot unpack zip file ${FLASH_FILENAME}"
    fi
    flash_inner_path=$(echo -n ${FLASH_VERSION} | sed -r "s/([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9])/\1_\2_r\3_\4/")
    flash_inner_file=$(echo -n ${FLASH_VERSION} | sed -r "s/([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9])/\1_\2r\3_\4/")
    if ! tar -xf ${flash_inner_path}_64bit/flashplayer${flash_inner_file}_linux.x86_64.tar.gz ; then
        exit_with_error "Cannot unpack inner flash tar file"
    fi
    if ! install -m 644 libflashplayer.so ${FLASH_DIR} ; then
        exit_with_error "Cannot install libflashplayer.so"
    fi
    popd

    echo "Symlinking the plugin shared objects"
    ln -s ${DEST_DIR}/jre*/lib/amd64/libnpjp2.so ${PLUGINS_DIR}
    ln -s ${FLASH_DIR}/libflashplayer.so ${PLUGINS_DIR}

    echo "Adding to desktop"
    mkdir -p ${DESKTOP_DIR}

    # Mozilla does not provide a .desktop file, so we need to construct one
    cat <<EOF > ${DESKTOP_DIR}/firefox.desktop
[Desktop Entry]
Version=1.0
Name=Firefox
Comment=Browse the World Wide Web
Comment[ar]=تصفح الشبكة العنكبوتية العالمية
Comment[ast]=Restola pela Rede
Comment[bn]=ইন্টারনেট ব্রাউজ করুন
Comment[ca]=Navegueu per la web
Comment[cs]=Prohlížení stránek World Wide Webu
Comment[da]=Surf på internettet
Comment[de]=Im Internet surfen
Comment[el]=Μπορείτε να περιηγηθείτε στο διαδίκτυο (Web)
Comment[es]=Navegue por la web
Comment[et]=Lehitse veebi
Comment[fa]=صفحات شبکه جهانی اینترنت را مرور نمایید
Comment[fi]=Selaa Internetin WWW-sivuja
Comment[fr]=Naviguer sur le Web
Comment[gl]=Navegar pola rede
Comment[he]=גלישה ברחבי האינטרנט
Comment[hr]=Pretražite web
Comment[hu]=A világháló böngészése
Comment[it]=Esplora il web
Comment[ja]=ウェブを閲覧します
Comment[ko]=웹을 돌아 다닙니다
Comment[ku]=Li torê bigere
Comment[lt]=Naršykite internete
Comment[nb]=Surf på nettet
Comment[nl]=Verken het internet
Comment[nn]=Surf på nettet
Comment[no]=Surf på nettet
Comment[pl]=Przeglądanie stron WWW 
Comment[pt]=Navegue na Internet
Comment[pt_BR]=Navegue na Internet
Comment[ro]=Navigați pe Internet
Comment[ru]=Доступ в Интернет
Comment[sk]=Prehliadanie internetu
Comment[sl]=Brskajte po spletu
Comment[sv]=Surfa på webben
Comment[tr]=İnternet'te Gezinin
Comment[ug]=دۇنيادىكى توربەتلەرنى كۆرگىلى بولىدۇ
Comment[uk]=Перегляд сторінок Інтернету
Comment[vi]=Để duyệt các trang web
Comment[zh_CN]=浏览互联网
Comment[zh_TW]=瀏覽網際網路
GenericName=Web Browser
GenericName[ar]=متصفح ويب
GenericName[ast]=Restolador Web
GenericName[bn]=ওয়েব ব্রাউজার
GenericName[ca]=Navegador web
GenericName[cs]=Webový prohlížeč
GenericName[da]=Webbrowser
GenericName[el]=Περιηγητής διαδικτύου
GenericName[es]=Navegador web
GenericName[et]=Veebibrauser
GenericName[fa]=مرورگر اینترنتی
GenericName[fi]=WWW-selain
GenericName[fr]=Navigateur Web
GenericName[gl]=Navegador Web
GenericName[he]=דפדפן אינטרנט
GenericName[hr]=Web preglednik
GenericName[hu]=Webböngésző
GenericName[it]=Browser web
GenericName[ja]=ウェブ・ブラウザ
GenericName[ko]=웹 브라우저
GenericName[ku]=Geroka torê
GenericName[lt]=Interneto naršyklė
GenericName[nb]=Nettleser
GenericName[nl]=Webbrowser
GenericName[nn]=Nettlesar
GenericName[no]=Nettleser
GenericName[pl]=Przeglądarka WWW
GenericName[pt]=Navegador Web
GenericName[pt_BR]=Navegador Web
GenericName[ro]=Navigator Internet
GenericName[ru]=Веб-браузер
GenericName[sk]=Internetový prehliadač
GenericName[sl]=Spletni brskalnik
GenericName[sv]=Webbläsare
GenericName[tr]=Web Tarayıcı
GenericName[ug]=توركۆرگۈ
GenericName[uk]=Веб-браузер
GenericName[vi]=Trình duyệt Web
GenericName[zh_CN]=网络浏览器
GenericName[zh_TW]=網路瀏覽器
Keywords=Internet;WWW;Browser;Web;Explorer
Keywords[ar]=انترنت;إنترنت;متصفح;ويب;وب
Keywords[ast]=Internet;WWW;Restolador;Web;Esplorador
Keywords[ca]=Internet;WWW;Navegador;Web;Explorador;Explorer
Keywords[cs]=Internet;WWW;Prohlížeč;Web;Explorer
Keywords[da]=Internet;Internettet;WWW;Browser;Browse;Web;Surf;Nettet
Keywords[de]=Internet;WWW;Browser;Web;Explorer;Webseite;Site;surfen;online;browsen
Keywords[el]=Internet;WWW;Browser;Web;Explorer;Διαδίκτυο;Περιηγητής;Firefox;Φιρεφοχ;Ιντερνετ
Keywords[es]=Explorador;Internet;WWW
Keywords[fi]=Internet;WWW;Browser;Web;Explorer;selain;Internet-selain;internetselain;verkkoselain;netti;surffaa
Keywords[fr]=Internet;WWW;Browser;Web;Explorer;Fureteur;Surfer;Navigateur
Keywords[he]=דפדפן;אינטרנט;רשת;אתרים;אתר;פיירפוקס;מוזילה;
Keywords[hr]=Internet;WWW;preglednik;Web
Keywords[hu]=Internet;WWW;Böngésző;Web;Háló;Net;Explorer
Keywords[it]=Internet;WWW;Browser;Web;Navigatore
Keywords[is]=Internet;WWW;Vafri;Vefur;Netvafri;Flakk
Keywords[ja]=Internet;WWW;Web;インターネット;ブラウザ;ウェブ;エクスプローラ
Keywords[nb]=Internett;WWW;Nettleser;Explorer;Web;Browser;Nettside
Keywords[nl]=Internet;WWW;Browser;Web;Explorer;Verkenner;Website;Surfen;Online 
Keywords[pt]=Internet;WWW;Browser;Web;Explorador;Navegador
Keywords[pt_BR]=Internet;WWW;Browser;Web;Explorador;Navegador
Keywords[ru]=Internet;WWW;Browser;Web;Explorer;интернет;браузер;веб;файрфокс;огнелис
Keywords[sk]=Internet;WWW;Prehliadač;Web;Explorer
Keywords[sl]=Internet;WWW;Browser;Web;Explorer;Brskalnik;Splet
Keywords[tr]=İnternet;WWW;Tarayıcı;Web;Gezgin;Web sitesi;Site;sörf;çevrimiçi;tara
Keywords[uk]=Internet;WWW;Browser;Web;Explorer;Інтернет;мережа;переглядач;оглядач;браузер;веб;файрфокс;вогнелис;перегляд
Keywords[vi]=Internet;WWW;Browser;Web;Explorer;Trình duyệt;Trang web
Keywords[zh_CN]=Internet;WWW;Browser;Web;Explorer;网页;浏览;上网;火狐;Firefox;ff;互联网;网站;
Keywords[zh_TW]=Internet;WWW;Browser;Web;Explorer;網際網路;網路;瀏覽器;上網;網頁;火狐
Exec=${DEST_DIR}/firefox/firefox %u
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=${DEST_DIR}/firefox.png
Categories=GNOME;GTK;Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
StartupNotify=true
Actions=NewWindow;NewPrivateWindow;

[Desktop Action NewWindow]
Name=Open a New Window
Name[ar]=افتح نافذة جديدة
Name[ast]=Abrir una ventana nueva
Name[bn]=Abrir una ventana nueva
Name[ca]=Obre una finestra nova
Name[cs]=Otevřít nové okno
Name[da]=Åbn et nyt vindue
Name[de]=Ein neues Fenster öffnen
Name[el]=Άνοιγμα νέου παραθύρου
Name[es]=Abrir una ventana nueva
Name[fi]=Avaa uusi ikkuna
Name[fr]=Ouvrir une nouvelle fenêtre
Name[gl]=Abrir unha nova xanela
Name[he]=פתיחת חלון חדש
Name[hr]=Otvori novi prozor
Name[hu]=Új ablak nyitása
Name[it]=Apri una nuova finestra
Name[ja]=新しいウィンドウを開く
Name[ko]=새 창 열기
Name[ku]=Paceyeke nû veke
Name[lt]=Atverti naują langą
Name[nb]=Åpne et nytt vindu
Name[nl]=Nieuw venster openen
Name[pt]=Abrir nova janela
Name[pt_BR]=Abrir nova janela
Name[ro]=Deschide o fereastră nouă
Name[ru]=Новое окно
Name[sk]=Otvoriť nové okno
Name[sl]=Odpri novo okno
Name[sv]=Öppna ett nytt fönster
Name[tr]=Yeni pencere aç 
Name[ug]=يېڭى كۆزنەك ئېچىش
Name[uk]=Відкрити нове вікно
Name[vi]=Mở cửa sổ mới
Name[zh_CN]=新建窗口
Name[zh_TW]=開啟新視窗
Exec=${DEST_DIR}/firefox/firefox -new-window
OnlyShowIn=Unity;

[Desktop Action NewPrivateWindow]
Name=Open a New Private Window
Name[ar]=افتح نافذة جديدة للتصفح الخاص
Name[ca]=Obre una finestra nova en mode d'incògnit
Name[de]=Ein neues privates Fenster öffnen
Name[es]=Abrir una ventana privada nueva
Name[fi]=Avaa uusi yksityinen ikkuna
Name[fr]=Ouvrir une nouvelle fenêtre de navigation privée
Name[he]=פתיחת חלון גלישה פרטית חדש
Name[hu]=Új privát ablak nyitása
Name[it]=Apri una nuova finestra anonima
Name[nb]=Åpne et nytt privat vindu
Name[ru]=Новое приватное окно
Name[sl]=Odpri novo okno zasebnega brskanja
Name[tr]=Yeni bir pencere aç
Name[uk]=Відкрити нове вікно у потайливому режимі
Name[zh_TW]=開啟新隱私瀏覽視窗
Exec=${DEST_DIR}/firefox/firefox -private-window
OnlyShowIn=Unity;
EOF
    
    cp ${TEMP_DIR}/${ICON_FILENAME} ${DEST_DIR}
    update-desktop-database ${DESKTOP_DIR}
    eos-add-to-desktop firefox
}

get_firefox_lang
download_packages
install_packages

rm -rf ${TEMP_DIR}

exit 0
